development:
  adapter: postgresql
  encoding: unicode
  database: microblog_dev
  pool: 5
  username: blob
  password: password
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: microblog_prod
  pool: 5
  username: blob
  password: password
  timeout: 5000

stage:
  adapter: postgresql
  encoding: unicode
  database: microblog_stage
  pool: 5
  username: blob
  password: password
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: microblog_test
  pool: 5
  username: blob
  password: password
  timeout: 5000